# Change these first
owner: LANDIT2021 # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Rocket Server (Prod - NY1)
    url: http://rocket.landit.pe
  - name: Cloud Server (Prod - NY1)
    url: http://app.landit.pe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.landit.pe
  theme: night
  # baseUrl: /your-repo-name
  # logoUrl: https://landit.pe/images/Recurso-2Logo-LANDIT.svg
  favicon: https://landit.pe/images/favicon.png
  name: Landit - Status
  introTitle: "**About This Site**"
  introMessage: This site provides real-time information on the availability of our cloud services. Rocket is the production server where we maintain applications that require high availability and resources on demand. Sandbox is the experimentation server where we run new software.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
